apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm2
  namespace: argocd
data:
  policy.csv: |
    p, role:image-updater, applications, get, gitops-galaxy/*, allow
    p, role:image-updater, applications, update, gitops-galaxy/*, allow
    p, role:image-updater, applications, action/*, gitops-galaxy/*, allow
    g, image-updater, role:image-updater

