namespace:
  name: app-staging

frontend:
  image:
    repository: docker.io/rasmusjoenurm/frontend
    tag: "1.0.29"
  replicaCount: 2

backend:
  image:
    repository: docker.io/rasmusjoenurm/backend
    tag: "1.0.29"
  replicaCount: 2

ingress:
  enabled: false

