apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elastic-credentials
  namespace: elastic
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: elastic-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/gitops-galaxy/elastic
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/gitops-galaxy/elastic
        property: password

