apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:9.1.4
          ports:
            - containerPort: 5044
              name: beats
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: password
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: logstash-alert-webhook
                  key: url
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: pipeline
          configMap:
            name: logstash-pipeline

