apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-exporter-dsn
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgres-exporter-dsn
    creationPolicy: Owner
  data:
    - secretKey: DATA_SOURCE_NAME
      remoteRef:
        key: secret/data/gitops-galaxy/dev/database
        property: datasource_name

