{{- if not .Values.externalSecrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.keys.host }}: "{{ .Values.database.host }}"
  {{ .Values.database.keys.port }}: "{{ .Values.database.port }}"
  {{ .Values.database.keys.database }}: "{{ .Values.database.name }}"
  {{ .Values.database.keys.username }}: "{{ .Values.database.username }}"
  {{ .Values.database.keys.password }}: "{{ .Values.database.password }}"
  {{ .Values.appSecrets.keys.jwt }}: "{{ .Values.appSecrets.jwt_key }}"
{{- end }}


