{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ .Values.database.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.keys.host }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.host }}
        property: host
    - secretKey: {{ .Values.database.keys.port }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.port }}
        property: port
    - secretKey: {{ .Values.database.keys.database }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.database }}
        property: database
    - secretKey: {{ .Values.database.keys.username }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.username }}
        property: username
    - secretKey: {{ .Values.database.keys.password }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.password }}
        property: password
    - secretKey: {{ .Values.appSecrets.keys.jwt }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.jwt }}
        property: jwt_key
{{- end }}
