apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend


    probe:
      readinessprobe:
        httpGet:
          targetPort: 80
          targetPath: /health
    spec:
      containers:
        - name: backend
          image: rasmusjoenurm/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"